# Generated by Django 3.2.6 on 2021-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='kkk', unique=True),
            preserve_default=False,
        ),
    ]
