# Generated by Django 3.2.6 on 2021-09-04 07:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('sumario', models.CharField(max_length=150)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
